FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./

RUN pip install --no-cache-dir \
    -r requirements.txt \
    -r requirements-dev.txt

COPY . .

EXPOSE 5000

CMD ["flask", "--app", "app.main", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
