apiVersion: v1
kind: ConfigMap
metadata:
  name: shopapi-config
  namespace: shopapi
data:
  FLASK_DEBUG: "false"
  LOG_LEVEL: "INFO"
  CACHE_DEFAULT_TIMEOUT: "300"
  GUNICORN_WORKERS: "3"
  GUNICORN_THREADS: "4"
  GUNICORN_TIMEOUT: "60"
