apiVersion: v1
kind: Secret
metadata:
  name: shopapi-secret
  namespace: shopapi
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME"
  JWT_SECRET_KEY: "CHANGE_ME"
  DATABASE_URL: "postgresql+psycopg://shopapi:CHANGE_ME@postgres:5432/shopapi"
  REDIS_URL: "redis://redis:6379/0"
